server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 175624
    driver-class-name: com.mysql.cj.jdbc.Driver

